baseURL = "/"
languageCode = "en-us"
title = "Selena Small"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""

[Params]
  disqusShortname = "selenasmall"

  Author = "Selena Small"
  description = "I R DEV"
  logoBig = "/images/osprey-logo.png"
  logoSmall = "/images/osprey-logo.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/osprey.png"
  twitter = "selenasmall88"
  linkedin = "selenasmall"
  github = "selenasmall"
  email = "selenawiththetattoo@gmail.com"
  googleTagManger = ""
  highlightJS = true
  copyright = true
  credit = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
[[menu.main]]
    name = "Test"
    url  = "/test"
    weight = 5